server:
  port: 8220
  servlet:
    context-path: /board
spring:
  application:
    name: board-rs
  main:
    banner-mode: off
  datasource:
    url: jdbc:log4jdbc:h2:file:~/h2db/board;AUTO_SERVER=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
scheduled:
  cron:
    expression:
      board:
        count: 0 0/1 * * * *